server:
  port: 8081

spring:
  application:
    name: customer
#  datasource:
#    url: ${DATABASE_URL}
#    username: ${POSTGRES_USER}
#    password: ${POSTGRES_USER}
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: 'true'
#    hibernate:
#      ddl-auto: update
#      show_sql: 'true'




