version: '3.8'

services:
  postgres:
    container_name: postgres-db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - $HOME/database/security:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    expose:
      - 5432
    environment:
      POSTGRES_DB: backend_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      SERVICE_TAGS: prod
      SERVICE_NAME: postgresdb_security
    networks:
      - security_network

  security_service:
    build:
      context: ./backend  # Adjust the context path as per your project structure
      dockerfile: Dockerfile  # Specify the Dockerfile name if it's different
    container_name: security_service_container
    restart: unless-stopped
    ports:
      - "8081:8081"
    expose:
      - 8081
    env_file:
      - docker-application.env
    depends_on:
      - postgres
    networks:
      - security_network

networks:
  security_network:
    driver: bridge
