spring:
  application:
    name: simple-api
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        transaction:
          jta:
            platform: org.hibernate.service.jta.platform.internal.WeblogicJtaPlatform
    hibernate:
      ddl-auto: update
      show_sql: 'true'


server:
  port: 8082