server:
  port: 8081

spring:
  application:
    name: simple-api
  datasource:
    url: jdbc:postgresql:http//localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: none
      show_sql: 'true'




