### Send POST request with json body
POST http://localhost:8080/api/v1/product/create
Content-Type: application/json

{
  "name": "Headphones",
  "description": "Beat By Dre",
  "price": 50.99
}

### Return all product records
GET http://localhost:8080/api/v1/product

### Get product By Id
GET http://localhost:8080/api/v1/product/11

###
GET http://localhost:8080/api/v1/order

###
### Send POST request with json body
POST http://localhost:8080/api/v1/order/create
Content-Type: application/json

{
  "orderLineItemDTOList": [
    {
      "skuCode": "SDDR",
      "price": 4500.99,
      "quantity": 12
    }
  ]
}

###
###
GET http://localhost:8080/api/v1/inventory/SSR

###