server:
  port: 8082

spring:
  application:
    name: backend-service
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_security_auth
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    flyway:
      locations: classpath:db/migration/
      baseline-on-migrate: true
      enabled: true
      baseline-description: "init"
      baseline-version: 0
      repair: true
      outOfOrder: true

  management:
    endpoints:
      web:
        exposure:
          include: "*"  # Exposes all endpoints; use specific endpoint IDs to limit exposure
        base-path: "/management"  # Base path for actuator endpoints
    endpoint:
      health:
        show-details: always  # Options are 'never', 'when-authorized', or 'always'
      info:
        enabled: true  # Enables the info endpoint

application:
  security:
    jwt:
      secret-key: "4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c"
      access-token-expiration: "86400000"
      refresh-token-expiration: "604800000"
